mysql:
  host: ${DOCKER_MYSQL_SPRINGBOOT_DEMO_MYSQL_HOST:localhost:3307}

spring:
  datasource:
    url: jdbc:mysql://${mysql.host}/docker_mysql_springboot_demo?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

server:
  port: 8081

  error:
    include-message: always